/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SpringBootWeb;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import hello.Application;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

//    public static void main(String[] args) {
//        System.out.println(new App().getGreeting());
//    }

    public static void main(String[] args) {
//        System.out.println(new App().getGreeting());
	SpringApplication.run(Application.class, args);
    }

}
